### ISSUE TITLE
`TypeError`: Cannot read properties of undefined (reading `'proportional_millionths'`)

### ISSUE THREAD

**Issue by RonaldCrb** [fedimint/ui#247]
everytime i refresh the browser at the guardian UI from the main dashboard, it will show the following errors along with just the blank screen:
![image](https://github.com/fedimint/ui/assets/40370316/cce3bc8d-68d4-4ac7-9efd-d10e5c2daae0)

```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'proportional_millionths')
    at GatewaysCard.tsx:66:49
    at Array.map (<anonymous>)
    at GatewaysCard.tsx:65:5
    at Object.Xi [as useMemo] (react-dom.production.min.js:179:119)
    at t.useMemo (react.production.min.js:25:208)
    at iu (GatewaysCard.tsx:64:38)
    at Ci (react-dom.production.min.js:167:137)
    at ju (react-dom.production.min.js:197:258)
    at Cl (react-dom.production.min.js:292:88)
    at xs (react-dom.production.min.js:280:389)
fu @ react-dom.production.min.js:189
react-dom.production.min.js:283 Uncaught TypeError: Cannot read properties of undefined (reading 'proportional_millionths')
    at GatewaysCard.tsx:66:49
    at Array.map (<anonymous>)
    at GatewaysCard.tsx:65:5
    at Object.Xi [as useMemo] (react-dom.production.min.js:179:119)
    at t.useMemo (react.production.min.js:25:208)
    at iu (GatewaysCard.tsx:64:38)
    at Ci (react-dom.production.min.js:167:137)
    at ju (react-dom.production.min.js:197:258)
    at Cl (react-dom.production.min.js:292:88)
    at xs (react-dom.production.min.js:280:389)
```

this can be reproduced in both leaders and followers UIs

**Comment by wbobeirne** [comment]
I'm unable to replicate this using `yarn nix-gateway`, what version of fedimintd are you running off of?

**Comment by wbobeirne** [comment]
It looks like there was a breaking change to this API 2 weeks ago, it's all nested under an `info` key now 🙃 

https://github.com/fedimint/fedimint/commit/7f5149f0800ce8e3ef37b0a44e7706f7eb1eb62d
